import { Inter } from 'next/font/google'
import './globals.css'
import '@rainbow-me/rainbowkit/styles.css'
import { AppProvider } from '@/components/Appcontext'
import { Toaster } from 'react-hot-toast'
import Providers from '@/libs/rainbowProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Votechain',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppProvider>
          <Providers>{children}</Providers>
          <Toaster position='top-center' />
        </AppProvider>
      </body>
    </html>
  )
}
