export const states = [
  {
    label: 'Andhra Pradesh',
    value: 'AP',
    districts: [
      { label: 'Anantapur', value: 'AN' },
      { label: 'Chittoor', value: 'CH' },
      { label: 'East Godavari', value: 'EG' },
      { label: 'Guntur', value: 'GU' },
      { label: 'Kadapa', value: 'KA' },
      { label: 'Krishna', value: 'KR' },
      { label: 'Kurnool', value: 'KU' },
      { label: 'Nellore', value: 'NE' },
      { label: 'Prakasam', value: 'PR' },
      { label: 'Srikakulam', value: 'SR' },
      { label: 'Visakhapatnam', value: 'VI' },
      { label: 'Vizianagaram', value: 'VZ' },
      { label: 'West Godavari', value: 'WG' },
      { label: 'Y.S.R. Kadapa', value: 'YS' },
    ],
  },
  {
    label: 'Arunachal Pradesh',
    value: 'AR',
    districts: [
      { label: 'Tawang', value: 'TA' },
      { label: 'West Kameng', value: 'WK' },
      { label: 'East Kameng', value: 'EK' },
      { label: 'Papum Pare', value: 'PP' },
      { label: 'Kurung Kumey', value: 'KK' },
      { label: 'Kra Daadi', value: 'KD' },
      { label: 'Lower Subansiri', value: 'LS' },
      { label: 'Upper Subansiri', value: 'US' },
      { label: 'West Siang', value: 'WS' },
      { label: 'East Siang', value: 'ES' },
      { label: 'Siang', value: 'SI' },
      { label: 'Upper Siang', value: 'USI' },
      { label: 'Lower Siang', value: 'LSI' },
      { label: 'Lower Dibang Valley', value: 'LDV' },
    ],
  },
  {
    label: 'Kerala',
    value: 'KL',
    districts: [
      { label: 'Thiruvananthapuram', value: 'TV' },
      { label: 'Kollam', value: 'KM' },
      { label: 'Pathanamthitta', value: 'PT' },
      { label: 'Alappuzha', value: 'AL' },
      { label: 'Kottayam', value: 'KT' },
      { label: 'Idukki', value: 'ID' },
      { label: 'Ernakulam', value: 'ER' },
      { label: 'Thrissur', value: 'TS' },
      { label: 'Palakkad', value: 'PK' },
      { label: 'Malappuram', value: 'MP' },
      { label: 'Kozhikode', value: 'KZ' },
      { label: 'Wayanad', value: 'WD' },
      { label: 'Kannur', value: 'KN' },
      { label: 'Kasaragod', value: 'KD' },
    ],
  },
  {
    label: 'Tamil Nadu',
    value: 'TN',
    districts: [
      { label: 'Chennai', value: 'CN' },
      { label: 'Kanchipuram', value: 'KP' },
      { label: 'Tiruvallur', value: 'TR' },
      { label: 'Vellore', value: 'VL' },
      { label: 'Tiruvannamalai', value: 'TNM' },
      { label: 'Salem', value: 'SLM' },
      { label: 'Namakkal', value: 'NM' },
      { label: 'Erode', value: 'ED' },
      { label: 'Coimbatore', value: 'CB' },
      { label: 'The Nilgiris', value: 'TNL' },
      { label: 'Madurai', value: 'MDR' },
      { label: 'Theni', value: 'TH' },
      { label: 'Dindigul', value: 'DG' },
      { label: 'Virudhunagar', value: 'VD' },
    ],
  },
  {
    label: 'Jammu & Kashmir',
    value: 'JK',
    districts: [
      { label: 'Jammu', value: 'JM' },
      { label: 'Srinagar', value: 'SR' },
      { label: 'Kathua', value: 'KH' },
      { label: 'Udhampur', value: 'UD' },
      { label: 'Pulwama', value: 'PL' },
      { label: 'Anantnag', value: 'AN' },
      { label: 'Kupwara', value: 'KPW' },
      { label: 'Baramulla', value: 'BM' },
      { label: 'Bandipora', value: 'BP' },
      { label: 'Rajouri', value: 'RJ' },
      { label: 'Doda', value: 'DD' },
      { label: 'Kishtwar', value: 'KT' },
      { label: 'Leh', value: 'LH' },
      { label: 'Kargil', value: 'KR' },
    ],
  },
  {
    label: 'Goa',
    value: 'GA',
    districts: [
      { label: 'North Goa', value: 'NG' },
      { label: 'South Goa', value: 'SG' },
    ],
  },
  {
    label: 'Karnataka',
    value: 'KA',
    districts: [
      { label: 'Bagalkot', value: 'BG' },
      { label: 'Ballari', value: 'BL' },
      { label: 'Belagavi', value: 'BV' },
      { label: 'Bengaluru Rural', value: 'BR' },
      { label: 'Bengaluru Urban', value: 'BU' },
      { label: 'Bidar', value: 'BD' },
      { label: 'Chamarajanagar', value: 'CR' },
      { label: 'Chikkaballapur', value: 'CK' },
      { label: 'Chikkamagaluru', value: 'CM' },
      { label: 'Chitradurga', value: 'CT' },
      { label: 'Dakshina Kannada', value: 'DK' },
      { label: 'Davanagere', value: 'DV' },
      { label: 'Dharwad', value: 'DW' },
      { label: 'Gadag', value: 'GD' },
    ],
  },
  {
    label: 'Gujarat',
    value: 'GJ',
    districts: [
      { label: 'Ahmedabad', value: 'AH' },
      { label: 'Amreli', value: 'AM' },
      { label: 'Anand', value: 'AN' },
      { label: 'Aravalli', value: 'AR' },
      { label: 'Banaskantha', value: 'BN' },
      { label: 'Bharuch', value: 'BH' },
      { label: 'Bhavnagar', value: 'BV' },
      { label: 'Botad', value: 'BT' },
      { label: 'Chhota Udaipur', value: 'CU' },
      { label: 'Dahod', value: 'DH' },
      { label: 'Dang', value: 'DG' },
      { label: 'Devbhoomi Dwarka', value: 'DD' },
      { label: 'Gandhinagar', value: 'GN' },
      { label: 'Gir Somnath', value: 'GS' },
    ],
  },
]
